#!/bin/bash

echo $BASHPID > /var/run/undervoltWatch.pid

#killall -q undervoltWatch
#while pgrep -u $UID -x undervoltWatch >/dev/null; do sleep 1; done

echo "IGNORE_DEFAULTS=$IGNORE_DEFAULTS"
echo "iCoreOffset=$iCoreOffset"
echo "iGpuOffset=$iGpuOffset"
echo "iTargetTemp=$iTargetTemp"

# Change these values to desired offsets
if [ -z ${IGNORE_DEFAULTS+x} ]; then
	if [ -z ${iCoreOffset+x} ]; then
		iCoreOffset=-110
	fi
	if [ -z ${iGpuOffset+x} ]; then
		iGpuOffset=-75
	fi
	if [ -z ${iTargetTemp+x} ]; then
		iTargetTemp=70
	fi
fi

echo "iCoreOffset=$iCoreOffset"
echo "iGpuOffset=$iGpuOffset"
echo "iTargetTemp=$iTargetTemp"

if [ ${iCoreOffset+x} ]; then
	iCoreOffsetOpt="--core $iCoreOffset --cache $iCoreOffset"
fi
if [ ${iGpuOffset+x} ]; then
	iGpuOffsetOpt="--gpu $iGpuOffset"
fi
if [ ${iTargetTemp+x} ]; then
	iTargetTempOpt="--temp $iTargetTemp"
fi

echo "Command: undervolt $iCoreOffsetOpt $iGpuOffsetOpt $iTargetTempOpt"

while true
do
	sCurrentCoreOffset=$(undervolt -r | grep -m 1 core: )
	if [ "$sCurrentCoreOffset" == "core: 0.0 mV" ]; then
		echo UV not applied. Applying now...
		undervolt $iCoreOffsetOpt $iGpuOffsetOpt $iTargetTempOpt
		sCurrentCoreOffset=$(undervolt -r | grep -m 1 core: )
		if [ "$sCurrentCoreOffset" == "core: 0.0 mV" ]; then
			echo UV failed to apply.
		else 
			echo UV applied.
		fi
	else
		echo UV already applied.
	fi
	sleep 5
done
